import React from 'react';
import { ScrollView, StyleSheet, View, TouchableOpacity } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { Feather } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';
import { HollowText } from '../../components/common/HollowText';
import { colors, spacing } from '../../theme';

export function TermsOfServiceScreen() {
  const navigation = useNavigation();

  return (
    <SafeAreaView style={styles.safe} edges={['top']}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}>
          <Feather name="arrow-left" size={24} color={colors.textPrimary} />
        </TouchableOpacity>
        <HollowText variant="subheading" serif style={styles.headerTitle}>
          Terms of Service
        </HollowText>
        <View style={{ width: 24 }} />
      </View>

      <ScrollView
        style={styles.container}
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}
      >
        <HollowText variant="label" color={colors.textMuted} style={styles.updated}>
          Last updated: February 2026
        </HollowText>

        <HollowText variant="body" color={colors.textSecondary} style={styles.paragraph}>
          Please read these Terms of Service ("Terms") carefully before using the Hollow application ("Service") operated by Hollow ("us", "we", or "our").
        </HollowText>

        <HollowText variant="subheading" serif color={colors.amber} style={styles.sectionTitle}>
          1. Acceptance of Terms
        </HollowText>
        <HollowText variant="body" color={colors.textSecondary} style={styles.paragraph}>
          By accessing or using Hollow, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the Service.
        </HollowText>

        <HollowText variant="subheading" serif color={colors.amber} style={styles.sectionTitle}>
          2. Description of Service
        </HollowText>
        <HollowText variant="body" color={colors.textSecondary} style={styles.paragraph}>
          Hollow is a privacy-focused AI companion application that provides conversational AI services. The app stores data locally on your device and connects to third-party AI providers using API keys that you supply.
        </HollowText>

        <HollowText variant="subheading" serif color={colors.amber} style={styles.sectionTitle}>
          3. User Responsibilities
        </HollowText>
        <HollowText variant="body" color={colors.textSecondary} style={styles.paragraph}>
          You are responsible for maintaining the confidentiality of your API keys and any credentials stored within the application. You agree not to use the Service for any unlawful purpose or in any way that could damage, disable, or impair the Service.
        </HollowText>

        <HollowText variant="subheading" serif color={colors.amber} style={styles.sectionTitle}>
          4. Subscriptions & Payments
        </HollowText>
        <HollowText variant="body" color={colors.textSecondary} style={styles.paragraph}>
          Some features of Hollow require a paid subscription. Subscription fees are billed in advance on a recurring basis. You can cancel your subscription at any time through the App Store or Google Play Store. Refunds are handled according to the respective store's refund policy.
        </HollowText>

        <HollowText variant="subheading" serif color={colors.amber} style={styles.sectionTitle}>
          5. AI-Generated Content
        </HollowText>
        <HollowText variant="body" color={colors.textSecondary} style={styles.paragraph}>
          The AI responses provided by Hollow are generated by third-party language models and are for informational and conversational purposes only. They should not be considered professional advice (medical, legal, financial, or otherwise). We make no warranties regarding the accuracy or reliability of AI-generated content.
        </HollowText>

        <HollowText variant="subheading" serif color={colors.amber} style={styles.sectionTitle}>
          6. Intellectual Property
        </HollowText>
        <HollowText variant="body" color={colors.textSecondary} style={styles.paragraph}>
          The Hollow application, its original content, features, and functionality are and will remain the exclusive property of Hollow and its licensors. Your conversations and memories remain your own property.
        </HollowText>

        <HollowText variant="subheading" serif color={colors.amber} style={styles.sectionTitle}>
          7. Limitation of Liability
        </HollowText>
        <HollowText variant="body" color={colors.textSecondary} style={styles.paragraph}>
          In no event shall Hollow, its directors, employees, partners, agents, suppliers, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of data, or other intangible losses resulting from your use of the Service.
        </HollowText>

        <HollowText variant="subheading" serif color={colors.amber} style={styles.sectionTitle}>
          8. Termination
        </HollowText>
        <HollowText variant="body" color={colors.textSecondary} style={styles.paragraph}>
          We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease.
        </HollowText>

        <HollowText variant="subheading" serif color={colors.amber} style={styles.sectionTitle}>
          9. Changes to Terms
        </HollowText>
        <HollowText variant="body" color={colors.textSecondary} style={styles.paragraph}>
          We reserve the right to modify or replace these Terms at any time. We will provide notice of material changes through the application. Your continued use of the Service after changes constitutes acceptance of the new Terms.
        </HollowText>

        <HollowText variant="subheading" serif color={colors.amber} style={styles.sectionTitle}>
          10. Contact Us
        </HollowText>
        <HollowText variant="body" color={colors.textSecondary} style={styles.paragraph}>
          If you have any questions about these Terms, please contact us at:
        </HollowText>
        <HollowText variant="body" color={colors.amber} style={styles.paragraph}>
          legal@hollow-app.com
        </HollowText>

        <View style={styles.bottomSpacer} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
  },
  container: {
    flex: 1,
  },
  content: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xl,
    paddingBottom: spacing['3xl'],
  },
  updated: {
    marginBottom: spacing.xl,
  },
  sectionTitle: {
    marginTop: spacing.xl,
    marginBottom: spacing.sm,
  },
  paragraph: {
    marginBottom: spacing.md,
    lineHeight: 24,
  },
  bottomSpacer: {
    height: spacing['3xl'],
  },
});
